require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/employments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Employment. As you add validations to Employment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Employment.create! valid_attributes
      get employments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      employment = Employment.create! valid_attributes
      get employment_url(employment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_employment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      employment = Employment.create! valid_attributes
      get edit_employment_url(employment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Employment" do
        expect {
          post employments_url, params: { employment: valid_attributes }
        }.to change(Employment, :count).by(1)
      end

      it "redirects to the created employment" do
        post employments_url, params: { employment: valid_attributes }
        expect(response).to redirect_to(employment_url(Employment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Employment" do
        expect {
          post employments_url, params: { employment: invalid_attributes }
        }.to change(Employment, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post employments_url, params: { employment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested employment" do
        employment = Employment.create! valid_attributes
        patch employment_url(employment), params: { employment: new_attributes }
        employment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the employment" do
        employment = Employment.create! valid_attributes
        patch employment_url(employment), params: { employment: new_attributes }
        employment.reload
        expect(response).to redirect_to(employment_url(employment))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        employment = Employment.create! valid_attributes
        patch employment_url(employment), params: { employment: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested employment" do
      employment = Employment.create! valid_attributes
      expect {
        delete employment_url(employment)
      }.to change(Employment, :count).by(-1)
    end

    it "redirects to the employments list" do
      employment = Employment.create! valid_attributes
      delete employment_url(employment)
      expect(response).to redirect_to(employments_url)
    end
  end
end
